export default {
  products:[{
    _id: "1",
    name: "Reggie Jackson",
    category: "Topps",
    image: "/images/Reggie_Jackson.JPG",
    price: 5,
    brand: "Topps",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
  {
    _id: "2",
    name: "Wade Boggs",
    category: "Topps",
    image: "/images/Wade_Boggs.JPG",
    price: 15,
    brand: "Topps",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
    {
    _id: "3",
    name: "Ken Griffey Jr",
    category: "Topps",
    image: "/images/Griffey_Topps.JPG",
    price: 5,
    brand: "Topps",
    rating: 4.5,
    numReviews: 10,
    countInStock: 2,
  },
  {
    _id: "4",
    name: "Jose Canseco",
    category: "Topps",
    image: "/images/Jose_87.JPG",
    price: 3,
    brand: "Topps",
    rating: 4.5,
    numReviews: 10,
    countInStock: 3,
  },  {
    _id: "5",
    name: "Barry Bonds",
    category: "Topps",
    image: "/images/Barry_Bonds.JPG",
    price: 3,
    brand: "Topps",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
  {
    _id: "6",
    name: "Greg Maddux",
    category: "Donruss",
    image: "/images/Greg_Maddux.JPG",
    price: 9,
    brand: "Donruss",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
  {
    _id: "7",
    name: "Mark Mcgwire",
    category: "Donruss",
    image: "/images/Mark_Mg.JPG",
    price: 7,
    brand: "Donruss",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
  {
    _id: "8",
    name: "Jose Canseco",
    category: "Donruss",
    image: "/images/Jose_Donruss.JPG",
    price: 14,
    brand: "Donruss",
    rating: 4.5,
    numReviews: 10,
    countInStock: 1,
  },
]
}